import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {
   Container ,
   Text,
   Flex,
   Button,
   Divider,
   Link
} from '@chakra-ui/react'
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   <Container
   backgroundColor="#fff"
   p='13'
   >
   
    <Flex
    justifyContent= 'space-between'
    alignItems='center'
    >
    <Text
    color="#000"
    fontSize = '24px'
    fontWeight = '500'
    >Product Add</Text>
     <Flex
      gap="16px"
     >
     <Button
          background = 'transparent'
          color = '#000'
          boxShadow = '6px 5px'
          height= '39px'
          w="60px"
          as="a"
          border="0.5px solid #363636"
          href='./add-product'
     >ADD</Button>
      <Button
        background = 'transparent'
        color = '#000'
        boxShadow = '6px 5px'
        height= '39px'
        id="delete-product-btn"
      >MASS DELETE</Button>
     </Flex>
    </Flex>
    <Divider 
    h="3"
    backgroundColor="#000"
    />
   </Container>
    </div>
  )
}

export default Home
